services:
  app:
    container_name: filament-manager
    build: ./
    ports:
      - 80:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=`${DATABASE_USER}`
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  postgres:
