import { createSlice, createAsyncThunk } from '@reduxjs/toolkit'

const initialState = {
    jobList: [],
    error: null
}


const fetchJobListById = createAsyncThunk(
    'api/jobs/history/SpoolId',
    async (spoolId) => {
        try {
            const response = await fetch(`/api/jobs/history/${spoolId}`);
            return response.data;
        } catch (err) {
            return err;
        }

    }
)


export const jobSlice = createSlice({
    name: "jobs",
    initialState,
    reducers: {

    },
    extraReducers: (builder) => {
        builder
            .addCase(fetchJobListById.fulfilled, (state, action) => {
                // push the returned data to jobList
                state.jobList.push(action.payload);
            })
            .addCase(fetchJobListById.rejected, (state, action) => {
                state.payload.error = action.payload
            })
    }
})

// actions are auto generated by redu x for each reducer function.
export const { } = jobSlice.actions
export default jobSlice.reducer;